# POST https://adminlt.laravel.tk/api/login
# Accept: application/json
# Content-Type: application/json

# {
#     "email" : "tungocvan1@gmail.com",
#     "password" : "123456"
# } 

# POST https://adminlt.laravel.tk/api/users
# Accept: application/json
# Content-Type: application/json

# {
#   "id":1
# }

# GET https://adminlt.laravel.tk/api/users/3
# Accept: application/json
# Content-Type: application/json

# PUT https://adminlt.laravel.tk/api/users/4
# Accept: application/json
# Content-Type: application/json

# {
#   "password": "999999",
#   "role_name":"User",
#   "verified":true
# }

# POST https://adminlt.laravel.tk/api/bang-gia
# Accept: application/json
# Content-Type: application/json

# {
#     "user_id" : 1,
#     "product_ids" : [4,5,6],
#     "ten_khach_hang" : "Quý Bệnh Viện",
#     "ghi_chu"        : "",
#     "company":  [
#         {
#             "title" : "Bảng Báo giá",
#             "date":"11/11/2025",
#             "departments":"Từ Ngọc Vân"
#         }
#     ]
# }

# GET https://adminlt.laravel.tk/api/bang-bao-gia
# Accept: application/json
# Content-Type: application/json

# POST https://adminlt.laravel.tk/api/user/send-mail
# Headers: 
# Authorization: Bearer 11|umwEptnOhWX44yG4zRi0g9suNU9gdUJf3kHhqAD975cbbf19
# Accept: application/json
# Content-Type: application/json

# {  
#   "to": "hamadaqc01@gmail.com",
#   "subject": "Test Queue Mail",
#   "html": "<h1>Hello</h1><p>This is a test</p>",
#   "attachments": ["https://adminlt.laravel.tk/baogia/Bao_gia_20251115_135702.xlsx"]
# }

# php artisan user:sendmail 2 --to="hamadaqc01@gmail.com" --subject="Test Queue Mail" --html="<b>Hello HTML</b>"
# POST https://adminlt.laravel.tk/api/invoices
# Headers: 
# Accept: application/json
# Content-Type: application/json

# {  
#     "invoice_type": "sold"
# }

POST https://muasamcong.mpi.gov.vn/o/egp-portal-personal-page/services/smart/search_prc
Accept: application/json
Content-Type: application/json
Origin: https://muasamcong.mpi.gov.vn
Referer: https://muasamcong.mpi.gov.vn/web/guest/profile-info?p_p_id=egpportalpersonalpage_WAR_egpportalpersonalpage&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_egpportalpersonalpage_WAR_egpportalpersonalpage_render=personalUrl&menu=bid-pricing
Cookie: COOKIE_SUPPORT=true; _ga=GA1.1.1190451015.1752638579; _gtpk_ses.6946.ea8d=1; _gtpk_testcookie..undefined=1; 5321a273c51a75133e0fb1cd75e32e27=6506b7b56d361f7cb4fd3eb2f0486eb8; df5f782085f475fb47cf8ea13597bc51=77d13e0cc2eb246243293347f6a9adee; GUEST_LANGUAGE_ID=vi_VN; LFR_SESSION_STATE_20103=1763692786692; NSC_WT_QSE_QPSUBM_NTD_NQJ=ffffffffaf183e2245525d5f4f58455e445a4a4217de; JSESSIONID=wEdv_avkNJD-ujM7-3eeVqtk-LS3lI0r-2DAChlI.dc_app1_02; _ga_19996Z37EE=GS2.1.s1763690184$o340$g1$t1763693538$j53$l0$h0; _gtpk_id.6946.ea8d=3965934490a5af0a.1752638577.330.1763693540.1763690183.; LFR_SESSION_STATE_19909668=1763693542436

[
  {
    "pageSize": 20,
    "pageNumber": 0,
    "query": [
      {
        "index": "es-smart-pricing",
        "keyWord": "Goldridons",
        "keyWordNotMatch": "",
        "matchType": "exact",
        "matchFields": ["ten_thuoc", "ten_hoat_chat", "ma_tbmt"],
        "filters": [
          {
            "fieldName": "medicines",
            "searchType": "in",
            "fieldValues": ["0"]
          },
          {
            "fieldName": "type",
            "searchType": "in",
            "fieldValues": ["HANG_HOA"]
          },
          {
            "fieldName": "tab",
            "searchType": "in",
            "fieldValues": ["THUOC_TAN_DUOC"]
          }
        ]
      }
    ]
  }
]
